# Generated by Django 3.2.18 on 2023-03-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_title_article_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='change',
            new_name='title',
        ),
    ]
