# Generated by Django 3.2.18 on 2023-03-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230316_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
